import { useMemo, useState } from "react";
import { Search, SlidersHorizontal } from "lucide-react";
import { useSearchParams } from "react-router";
import { ProductCard } from "../../components/commerce/ProductCard";
import { SiteHeader } from "../../components/navigation/SiteHeader";
import { MobileDock } from "../../components/navigation/MobileDock";
import { catalogProducts } from "../../data/catalog";
import "./shop.css";
const categories=["All","Resin Art","Candle Making","Soap Making"];
const slugToCategory:Record<string,string>={"resin-art":"Resin Art","candle-making":"Candle Making","soap-making":"Soap Making","kits":"Creative Kits"};
export function ShopPage(){const [params,setParams]=useSearchParams();const initialCategory=slugToCategory[params.get("category")??""]??"All";const [query,setQuery]=useState(params.get("q")??"");const [category,setCategory]=useState(initialCategory);const products=useMemo(()=>{const needle=query.trim().toLowerCase();return catalogProducts.filter(product=>(category==="All"||product.category===category)&&(!needle||`${product.name} ${product.description} ${product.category}`.toLowerCase().includes(needle)))},[query,category]);const selectCategory=(value:string)=>{setCategory(value);const next=new URLSearchParams(params);if(value==="All")next.delete("category");else{const slug=Object.entries(slugToCategory).find(([,label])=>label===value)?.[0];if(slug)next.set("category",slug)}setParams(next,{replace:true})};return <div className="shop-page"><SiteHeader/><main className="q-container shop"><header className="shop__header"><p>QUORIN COLLECTION</p><h1 className="q-display">Find your next material.</h1><span>Explore tools, pigments and kits selected for hands-on makers.</span></header><div className="shop__toolbar"><label><Search size={18}/><input value={query} onChange={event=>{const value=event.target.value;setQuery(value);const next=new URLSearchParams(params);if(value)next.set("q",value);else next.delete("q");setParams(next,{replace:true})}} placeholder="Search products" aria-label="Search products"/></label><button type="button" aria-label="Product filters"><SlidersHorizontal size={18}/> Filters</button></div><div className="shop__chips" aria-label="Product categories">{categories.map(item=><button className={category===item?"is-active":""} aria-pressed={category===item} onClick={()=>selectCategory(item)} key={item}>{item}</button>)}</div><p className="shop__count">{products.length} {products.length===1?"product":"products"}</p>{products.length?<section className="shop__grid" aria-label="Products">{products.map(product=><a href={`/product/${product.id}`} key={product.id}><ProductCard product={product}/></a>)}</section>:<section className="shop__empty"><h2>No materials found.</h2><p>Try another search or explore a different craft.</p><button onClick={()=>{setQuery("");setCategory("All");setParams({}, {replace:true})}}>Clear search</button></section>}</main><MobileDock/></div>}
