import { ArrowRight, Gem, HeartHandshake, PackageCheck, Sparkles } from "lucide-react";
import { ProductCard } from "../../components/commerce/ProductCard";
import { MobileDock } from "../../components/navigation/MobileDock";
import { SiteHeader } from "../../components/navigation/SiteHeader";
import { SectionHeading } from "../../components/primitives/SectionHeading";
import { catalogProducts } from "../../data/catalog";
import "../../components/primitives/primitives.css";
import "./home.css";
const categories=[{title:"Resin Art",copy:"Pigments, molds and finishing essentials",image:"/PHOTOS/Resin/1.webp"},{title:"Candle Making",copy:"Wax, fragrance and tools for a warmer glow",image:"/PHOTOS/candle pigments/candle colour for canldle making (1).webp"},{title:"Soap Making",copy:"Thoughtful ingredients for small-batch craft",image:"/PHOTOS/Soap dye/1.webp"},{title:"Creative Kits",copy:"Everything you need to begin beautifully",image:"/PHOTOS/Soap Dye + mould/1.webp"}];
const values=[{icon:Gem,title:"Curated quality",copy:"Materials selected for makers who care about the finish."},{icon:PackageCheck,title:"Packed with care",copy:"Orders prepared thoughtfully so your supplies arrive ready to create."},{icon:HeartHandshake,title:"Made for makers",copy:"Practical guidance and a community that grows with your craft."},{icon:Sparkles,title:"Fresh inspiration",copy:"New materials, techniques and project ideas worth exploring."}];
export function HomePage(){return <div className="home-page"><SiteHeader/><main><section className="home-hero" aria-labelledby="home-hero-title"><div className="q-container home-hero__content"><p className="home-hero__eyebrow">Made for makers</p><h1 id="home-hero-title" className="q-display home-hero__title">Create what you imagine.</h1><p className="home-hero__copy">Premium supplies, thoughtful tools and inspiration for handcrafted work.</p><a className="home-hero__cta" href="/search">Explore the collection <ArrowRight size={18}/></a></div><div className="home-hero__image" aria-hidden="true"><img src="/PHOTOS/Resin/1.webp" alt=""/></div></section><section className="q-section home-categories"><div className="q-container"><SectionHeading eyebrow="Explore your craft" title="Made for the way you create" copy="Find materials and tools organized around the crafts you love."/><div className="home-categories__grid">{categories.map(category=><a className="category-card" href="/search" key={category.title}><div className="category-card__visual"><img src={category.image} alt="" loading="lazy"/></div><div className="category-card__body"><h3>{category.title}</h3><p>{category.copy}</p><span className="category-card__link">Shop collection <ArrowRight size={16}/></span></div></a>)}</div></div></section><section className="q-section home-values"><div className="q-container"><SectionHeading eyebrow="The QUORIN difference" title="Why makers shop with us"/><div className="home-values__grid">{values.map(({icon:Icon,title,copy})=><article className="value-card" key={title}><span className="value-card__icon"><Icon size={22}/></span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section><section className="q-section home-products"><div className="q-container"><div className="home-products__head"><SectionHeading eyebrow="Popular right now" title="Best sellers" align="left"/><a href="/search">View all <ArrowRight size={16}/></a></div><div className="home-products__grid">{catalogProducts.slice(0,4).map(product=><ProductCard product={product} key={product.id}/>)}</div></div></section><section className="q-section home-community"><div className="q-container home-community__panel"><p>THE CREATIVE COMMUNITY</p><h2 className="q-display">Make, learn, share — and keep creating.</h2><span>Project inspiration, thoughtful materials and new ideas from QUORIN.</span><a href="/search">Explore QUORIN <ArrowRight size={17}/></a></div></section></main><MobileDock/></div>}
