import { useEffect, useId, useRef, type ReactNode } from 'react';
import { motion } from 'framer-motion';
import { AlertCircle, Loader2, X } from 'lucide-react';

export function PageHeader({ title, subtitle, action }: { title: string; subtitle?: string; action?: ReactNode }) { return <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-8"><div><h1 className="text-2xl lg:text-3xl font-bold" style={{ color: 'var(--color-text-primary)' }}>{title}</h1>{subtitle && <p className="text-sm mt-1" style={{ color: 'var(--color-text-muted)' }}>{subtitle}</p>}</div>{action}</div>; }
export function Card({ children, className = '' }: { children: ReactNode; className?: string }) { return <div className={`rounded-2xl p-5 ${className}`} style={{ background: 'var(--color-surface)', border: '1px solid var(--color-border)' }}>{children}</div>; }
export function StatCard({ label, value, icon: Icon, accent }: { label: string; value: ReactNode; icon: typeof Loader2; accent?: boolean }) { return <Card><div className="flex items-center justify-between"><div><div className="text-xs tracking-[0.15em]" style={{ color: 'var(--color-text-muted)' }}>{label.toUpperCase()}</div><div className="text-2xl font-bold mt-1" style={{ color: accent ? 'var(--color-accent)' : 'var(--color-text-primary)' }}>{value}</div></div><div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{ background: accent ? 'var(--color-accent)' : 'var(--color-surface-hover)' }}><Icon size={18} color={accent ? 'white' : 'var(--color-text-muted)'} /></div></div></Card>; }
export function Loading({ label = 'Loading…' }: { label?: string }) { return <div className="flex flex-col items-center justify-center py-20" style={{ color: 'var(--color-text-muted)' }}><Loader2 size={28} className="animate-spin mb-3" /><span className="text-sm">{label}</span></div>; }
export function ErrorState({ message, retry }: { message: string; retry?: () => void }) { return <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex items-start justify-between gap-4 rounded-2xl p-5" style={{ background: 'var(--color-accent-soft)', border: '1px solid var(--color-border-subtle)', color: 'var(--color-destructive)' }}><div className="flex items-start gap-3"><AlertCircle size={20} className="flex-shrink-0 mt-0.5" /><div className="text-sm">{message}</div></div>{retry && <GhostButton onClick={retry}>Try again</GhostButton>}</motion.div>; }
export function EmptyState({ title, description, action }: { title: string; description?: string; action?: ReactNode }) { return <div className="flex flex-col items-center justify-center py-16 text-center"><div className="text-lg font-semibold mb-1" style={{ color: 'var(--color-text-primary)' }}>{title}</div>{description && <p className="text-sm max-w-sm" style={{ color: 'var(--color-text-muted)' }}>{description}</p>}{action && <div className="mt-4">{action}</div>}</div>; }
export function PrimaryButton({ children, onClick, type, disabled, className = '' }: { children: ReactNode; onClick?: () => void; type?: 'button' | 'submit'; disabled?: boolean; className?: string }) { return <button type={type ?? 'button'} onClick={onClick} disabled={disabled} className={`inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl text-sm font-semibold transition-opacity ${className}`} style={{ background: 'var(--color-accent)', color: 'white', opacity: disabled ? 0.6 : 1 }}>{children}</button>; }
export function GhostButton({ children, onClick, className = '', disabled = false }: { children: ReactNode; onClick?: () => void; className?: string; disabled?: boolean }) { return <button type="button" onClick={onClick} disabled={disabled} className={`inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium ${className}`} style={{ background: 'var(--color-surface)', color: 'var(--color-text-primary)', border: '1px solid var(--color-border-subtle)', opacity: disabled ? 0.6 : 1 }}>{children}</button>; }
export function DangerButton({ children, onClick, disabled, className = '' }: { children: ReactNode; onClick?: () => void; disabled?: boolean; className?: string }) { return <button type="button" onClick={onClick} disabled={disabled} className={`inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl text-sm font-semibold ${className}`} style={{ background: 'var(--color-destructive)', color: 'white', opacity: disabled ? 0.6 : 1 }}>{children}</button>; }
export function Badge({ children, tone = 'neutral' }: { children: ReactNode; tone?: 'neutral' | 'success' | 'warning' | 'danger' | 'accent' }) { const bg = { neutral: 'var(--color-surface-hover)', success: 'var(--color-accent-soft)', warning: 'rgba(250, 204, 21, 0.15)', danger: 'rgba(248, 113, 113, 0.15)', accent: 'var(--color-accent)' }[tone]; const color = tone === 'accent' ? 'white' : tone === 'success' ? 'var(--color-success)' : tone === 'danger' ? 'var(--color-destructive)' : tone === 'warning' ? '#b45309' : 'var(--color-text-secondary)'; return <span className="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-medium" style={{ background: bg, color }}>{children}</span>; }

export function Modal({ open, title, description, children, footer, onClose, maxWidth = 'max-w-lg' }: { open: boolean; title: string; description?: string; children: ReactNode; footer?: ReactNode; onClose: () => void; maxWidth?: string }) {
  const titleId = useId(); const descriptionId = useId(); const dialogRef = useRef<HTMLElement>(null); const previousFocus = useRef<HTMLElement | null>(null);
  useEffect(() => {
    if (!open) return;
    previousFocus.current = document.activeElement instanceof HTMLElement ? document.activeElement : null;
    const previousOverflow = document.body.style.overflow; document.body.style.overflow = 'hidden';
    const focusable = () => Array.from(dialogRef.current?.querySelectorAll<HTMLElement>('button:not([disabled]), [href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])') ?? []);
    requestAnimationFrame(() => focusable()[0]?.focus());
    const onKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') { event.preventDefault(); onClose(); return; } if (event.key !== 'Tab') return; const items = focusable(); if (!items.length) { event.preventDefault(); return; } const first = items[0]; const last = items[items.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } };
    window.addEventListener('keydown', onKeyDown);
    return () => { document.body.style.overflow = previousOverflow; window.removeEventListener('keydown', onKeyDown); previousFocus.current?.focus(); };
  }, [open, onClose]);
  if (!open) return null;
  return <div className="fixed inset-0 z-[150] flex items-center justify-center p-4" style={{ background: 'rgba(20,15,10,0.5)' }} onMouseDown={onClose} role="presentation"><section ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby={titleId} aria-describedby={description ? descriptionId : undefined} className={`w-full ${maxWidth} max-h-[calc(100dvh-2rem)] rounded-2xl overflow-hidden flex flex-col`} style={{ background: 'var(--color-surface)', border: '1px solid var(--color-border)' }} onMouseDown={(event) => event.stopPropagation()}><header className="flex items-start justify-between gap-4 p-6 pb-4 shrink-0"><div><h2 id={titleId} className="text-lg font-bold" style={{ color: 'var(--color-text-primary)' }}>{title}</h2>{description && <p id={descriptionId} className="text-sm mt-1" style={{ color: 'var(--color-text-muted)' }}>{description}</p>}</div><button type="button" onClick={onClose} aria-label="Close dialog" className="p-2 rounded-xl" style={{ color: 'var(--color-text-muted)', background: 'var(--color-surface-hover)' }}><X size={17} /></button></header><div className="px-6 pb-6 overflow-y-auto" data-lenis-prevent>{children}</div>{footer && <footer className="flex flex-wrap justify-end gap-2 px-6 py-4 shrink-0" style={{ borderTop: '1px solid var(--color-border-subtle)' }}>{footer}</footer>}</section></div>;
}
export function ConfirmDialog({ open, title, description, confirmLabel = 'Confirm', busy = false, destructive = false, onCancel, onConfirm }: { open: boolean; title: string; description: string; confirmLabel?: string; busy?: boolean; destructive?: boolean; onCancel: () => void; onConfirm: () => void }) { const action = destructive ? <DangerButton onClick={onConfirm} disabled={busy}>{busy ? <Loader2 size={14} className="animate-spin" /> : null}{confirmLabel}</DangerButton> : <PrimaryButton onClick={onConfirm} disabled={busy}>{busy ? <Loader2 size={14} className="animate-spin" /> : null}{confirmLabel}</PrimaryButton>; return <Modal open={open} title={title} description={description} onClose={busy ? () => undefined : onCancel} footer={<><GhostButton onClick={onCancel} disabled={busy}>Cancel</GhostButton>{action}</>}><div className="text-sm" style={{ color: 'var(--color-text-secondary)' }}>This action should only be completed when you are sure.</div></Modal>; }
