import { useEffect, useMemo, useState } from 'react';
import { NavLink, Outlet, useLocation, useNavigate } from 'react-router';
import { AnimatePresence, motion } from 'framer-motion';
import { BarChart3, Boxes, ExternalLink, FileBarChart, FolderTree, Image as ImageIcon, Layers, LayoutDashboard, LogOut, Menu, Package, ScrollText, Settings, ShoppingCart, Store, Ticket, UserCog, Users, X } from 'lucide-react';
import { useAdminAuth } from '@/contexts/AdminAuthContext';

interface NavItem { to: string; label: string; icon: typeof LayoutDashboard; }
const NAV_SECTIONS: { title: string; items: NavItem[] }[] = [
  { title: 'Overview', items: [{ to: '/admin', label: 'Dashboard', icon: LayoutDashboard }, { to: '/admin/analytics', label: 'Analytics', icon: BarChart3 }, { to: '/admin/analytics?view=reports', label: 'Reports', icon: FileBarChart }] },
  { title: 'Catalog', items: [{ to: '/admin/products', label: 'Products', icon: Package }, { to: '/admin/categories', label: 'Categories', icon: FolderTree }, { to: '/admin/collections', label: 'Collections', icon: Layers }, { to: '/admin/inventory', label: 'Inventory', icon: Boxes }, { to: '/admin/media', label: 'Media Library', icon: ImageIcon }] },
  { title: 'Sales', items: [{ to: '/admin/orders', label: 'Orders', icon: ShoppingCart }, { to: '/admin/customers', label: 'Customers', icon: Users }, { to: '/admin/coupons', label: 'Coupons & Promotions', icon: Ticket }] },
  { title: 'System', items: [{ to: '/admin/settings', label: 'Settings', icon: Settings }, { to: '/admin/admins', label: 'Admins & Roles', icon: UserCog }, { to: '/admin/activity', label: 'Activity Logs', icon: ScrollText }] },
];

export default function AdminLayout() {
  const { user, logout } = useAdminAuth();
  const navigate = useNavigate();
  const location = useLocation();
  const [mobileOpen, setMobileOpen] = useState(false);
  const currentPath = `${location.pathname}${location.search}`;
  const current = useMemo(() => NAV_SECTIONS.flatMap((section) => section.items).find((item) => item.to === currentPath) ?? NAV_SECTIONS.flatMap((section) => section.items).find((item) => item.to === location.pathname) ?? (location.pathname === '/admin' ? NAV_SECTIONS[0].items[0] : null), [currentPath, location.pathname]);
  useEffect(() => { setMobileOpen(false); }, [location.pathname, location.search]);
  useEffect(() => {
    if (!mobileOpen) return;
    const onKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') setMobileOpen(false); };
    const previous = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    window.addEventListener('keydown', onKeyDown);
    return () => { document.body.style.overflow = previous; window.removeEventListener('keydown', onKeyDown); };
  }, [mobileOpen]);
  const handleLogout = () => { logout(); navigate('/admin/login', { replace: true }); };

  const SidebarContent = <div className="flex flex-col h-full"><div className="px-5 py-5 flex items-center gap-3" style={{ borderBottom: '1px solid var(--color-border-subtle)' }}><div className="w-10 h-10 rounded-2xl flex items-center justify-center" style={{ background: 'var(--color-accent)' }}><Store size={19} color="white" /></div><div><div className="text-sm font-bold tracking-[0.16em]" style={{ color: 'var(--color-text-primary)' }}>QUORIN</div><div className="text-[10px] tracking-[0.18em]" style={{ color: 'var(--color-text-muted)' }}>MANAGEMENT</div></div></div><nav aria-label="Admin navigation" className="flex-1 overflow-y-auto px-3 py-4 space-y-6" data-lenis-prevent>{NAV_SECTIONS.map((section) => <section key={section.title}><div className="px-3 mb-2 text-[10px] tracking-[0.2em] font-semibold" style={{ color: 'var(--color-text-muted)' }}>{section.title.toUpperCase()}</div><div className="space-y-1">{section.items.map((item) => { const active = item.to === currentPath || (item.to === location.pathname && !location.search); return <NavLink key={item.to} to={item.to} end={item.to === '/admin'} className={`flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm transition-[background,color,transform] ${active ? 'font-semibold' : 'hover:translate-x-0.5'}`} style={{ background: active ? 'var(--color-accent)' : 'transparent', color: active ? 'white' : 'var(--color-text-secondary)' }}><item.icon size={18} aria-hidden="true" />{item.label}</NavLink>; })}</div></section>)}</nav><div className="px-3 py-4 space-y-2" style={{ borderTop: '1px solid var(--color-border-subtle)' }}><a href="/" target="_blank" rel="noreferrer" className="flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm w-full" style={{ color: 'var(--color-text-secondary)' }}><ExternalLink size={18} />View Storefront</a><div className="flex items-center gap-3 px-3 py-2 rounded-xl" style={{ background: 'var(--color-background)' }}><div className="w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold" style={{ background: 'var(--color-accent)', color: 'white' }}>{(user?.first_name?.[0] ?? user?.email?.[0] ?? 'A').toUpperCase()}</div><div className="flex-1 min-w-0"><div className="text-sm font-medium truncate" style={{ color: 'var(--color-text-primary)' }}>{user?.first_name ? `${user.first_name} ${user.last_name ?? ''}`.trim() : user?.email ?? 'Admin'}</div><div className="text-xs truncate" style={{ color: 'var(--color-text-muted)' }}>{user?.email}</div></div><button type="button" onClick={handleLogout} aria-label="Sign out" className="p-2 rounded-lg" style={{ color: 'var(--color-text-muted)' }}><LogOut size={16} /></button></div></div></div>;

  return <div className="min-h-screen flex" style={{ background: 'var(--color-background)' }}><aside className="hidden lg:flex flex-col w-64 fixed inset-y-0 left-0 z-30" style={{ background: 'var(--color-surface)', borderRight: '1px solid var(--color-border)' }}>{SidebarContent}</aside><AnimatePresence>{mobileOpen && <><motion.button type="button" aria-label="Close navigation" className="fixed inset-0 z-40 lg:hidden w-full h-full cursor-default" style={{ background: 'rgba(20,15,10,0.5)' }} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setMobileOpen(false)} /><motion.aside aria-label="Mobile admin navigation" className="fixed inset-y-0 left-0 z-50 w-[min(86vw,19rem)] lg:hidden" style={{ background: 'var(--color-surface)' }} initial={{ x: -340 }} animate={{ x: 0 }} exit={{ x: -340 }} transition={{ type: 'spring', stiffness: 300, damping: 30 }}>{SidebarContent}<button type="button" className="absolute top-4 right-4 p-2 rounded-xl" onClick={() => setMobileOpen(false)} aria-label="Close menu" style={{ color: 'var(--color-text-primary)', background: 'var(--color-background)' }}><X size={18} /></button></motion.aside></>}</AnimatePresence><div className="flex-1 lg:ml-64 flex flex-col min-w-0"><header className="sticky top-0 z-20 flex items-center justify-between gap-3 px-4 lg:px-8 py-3.5" style={{ background: 'color-mix(in srgb, var(--color-surface) 92%, transparent)', borderBottom: '1px solid var(--color-border-subtle)', backdropFilter: 'blur(18px)' }}><div className="flex items-center gap-3 min-w-0"><button type="button" className="lg:hidden p-2 rounded-xl" onClick={() => setMobileOpen(true)} aria-label="Open menu" style={{ background: 'var(--color-background)', color: 'var(--color-text-primary)' }}><Menu size={20} /></button><div className="min-w-0"><div className="text-[10px] tracking-[0.18em]" style={{ color: 'var(--color-text-muted)' }}>QUORIN ADMIN</div><div className="text-sm font-semibold truncate" style={{ color: 'var(--color-text-primary)' }}>{current?.label ?? 'Management Console'}</div></div></div><a href="/" target="_blank" rel="noreferrer" className="hidden sm:inline-flex items-center gap-2 px-3 py-2 rounded-xl text-xs font-medium" style={{ color: 'var(--color-text-secondary)', background: 'var(--color-background)', border: '1px solid var(--color-border-subtle)' }}>Storefront <ExternalLink size={14} /></a></header><main className="flex-1 p-4 sm:p-6 lg:p-8 max-w-[1600px] w-full mx-auto"><Outlet /></main></div></div>;
}
