import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import { catalogProducts, type CatalogProduct } from "../data/catalog";
type CartLine={product:CatalogProduct;quantity:number};
type StoredState={wishlist:string[];cart:{id:string;quantity:number}[]};
type ShopState={wishlist:string[];cart:CartLine[];toggleWishlist:(id:string)=>void;addToCart:(id:string)=>void;changeQuantity:(id:string,delta:number)=>void;removeFromCart:(id:string)=>void;cartCount:number;subtotal:number};
const STORAGE_KEY="quorin:v3:shop";
const ShopContext=createContext<ShopState|null>(null);
function loadState():StoredState{if(typeof window==="undefined")return{wishlist:[],cart:[]};try{const raw=window.localStorage.getItem(STORAGE_KEY);if(!raw)return{wishlist:[],cart:[]};const parsed=JSON.parse(raw) as StoredState;return{wishlist:Array.isArray(parsed.wishlist)?parsed.wishlist:[],cart:Array.isArray(parsed.cart)?parsed.cart:[]}}catch{return{wishlist:[],cart:[]}}}
export function ShopProvider({children}:{children:ReactNode}){const initial=loadState();const [wishlist,setWishlist]=useState<string[]>(initial.wishlist);const [cart,setCart]=useState<CartLine[]>(initial.cart.flatMap(line=>{const product=catalogProducts.find(item=>item.id===line.id);return product?[{product,quantity:Math.max(1,line.quantity)}]:[]}));useEffect(()=>{const state:StoredState={wishlist,cart:cart.map(line=>({id:line.product.id,quantity:line.quantity}))};window.localStorage.setItem(STORAGE_KEY,JSON.stringify(state))},[wishlist,cart]);const toggleWishlist=(id:string)=>setWishlist(items=>items.includes(id)?items.filter(item=>item!==id):[...items,id]);const addToCart=(id:string)=>setCart(lines=>{const existing=lines.find(line=>line.product.id===id);if(existing)return lines.map(line=>line.product.id===id?{...line,quantity:line.quantity+1}:line);const product=catalogProducts.find(item=>item.id===id);return product?[...lines,{product,quantity:1}]:lines});const changeQuantity=(id:string,delta:number)=>setCart(lines=>lines.map(line=>line.product.id===id?{...line,quantity:Math.max(1,line.quantity+delta)}:line));const removeFromCart=(id:string)=>setCart(lines=>lines.filter(line=>line.product.id!==id));const value=useMemo(()=>({wishlist,cart,toggleWishlist,addToCart,changeQuantity,removeFromCart,cartCount:cart.reduce((sum,line)=>sum+line.quantity,0),subtotal:cart.reduce((sum,line)=>sum+line.product.price*line.quantity,0)}),[wishlist,cart]);return <ShopContext.Provider value={value}>{children}</ShopContext.Provider>}
export function useShop(){const context=useContext(ShopContext);if(!context)throw new Error("useShop must be used within ShopProvider");return context}
